// ──────────────────────────────────────────
// xSyna Central – Feature definitions
// ──────────────────────────────────────────

export const MODULE_FEATURES = [
  "home",
  "worktime",
  "tasks",
  "calendar",
  "contacts",
  "chat",
  "vault",
  "workspace",
  "basics",
  "news",
  "docs",
  "apply",
  "teams",
  "security",
  "payments",
  "account",
  "settings",
  "auftrag",
  "admin",
] as const;

export const ACTION_FEATURES = [
  "worktime.manage",
  "contacts.manage",
  "calendar.manage",
  "tasks.manage",
  "teams.manage",
  "teams.permissions",
  "security.all",
  "settings.admin",
  "maintenance.manage",
  "news.manage",
  "docs.manage",
  "basics.manage",
  "payments.manage",
  "apply.manage",
  "vault.shared",
  "sso.admin",
  "notify.manage",
  "support.manage",
  "workspace.manage",
  "auftrag.manage",
] as const;

export type ModuleFeature = (typeof MODULE_FEATURES)[number];
export type ActionFeature = (typeof ACTION_FEATURES)[number];
export type Feature = ModuleFeature | ActionFeature;

export const FEATURE_DESCRIPTIONS: Record<Feature, string> = {
  home: "Dashboard mit Profil-Quick-Login und Uhrzeit",
  worktime: "Arbeitszeiterfassung",
  "worktime.manage": "Alle Arbeitszeiten verwalten",
  tasks: "Aufgaben-Tracking",
  "tasks.manage": "Alle Aufgaben verwalten",
  calendar: "Kalender",
  "calendar.manage": "Alle Kalender-Einträge verwalten",
  contacts: "Kontaktliste",
  "contacts.manage": "Alle Kontakte verwalten",
  chat: "Chat / Notizen",
  vault: "Tresor (Passwörter)",
  "vault.shared": "Geteilte Tresor-Einträge verwalten",
  workspace: "Arbeitsbereich (Docs, Files)",
  "workspace.manage": "Alle Workspace-Docs verwalten",
  basics: "Grundlagen / Wiki",
  "basics.manage": "Grundlagen verwalten",
  news: "Neuigkeiten",
  "news.manage": "Neuigkeiten verwalten",
  docs: "Dokumente",
  "docs.manage": "Dokumente verwalten",
  apply: "Bewerbungen",
  "apply.manage": "Bewerbungen verwalten",
  teams: "Teams & Ränge",
  "teams.manage": "Teams verwalten",
  "teams.permissions": "Team-Berechtigungen verwalten",
  security: "Sicherheit / Logs",
  "security.all": "Alle Sicherheitsfunktionen",
  payments: "Zahlungen / Finanzen",
  "payments.manage": "Zahlungen verwalten",
  account: "Mein Account",
  settings: "Einstellungen",
  "settings.admin": "Admin-Einstellungen verwalten",
  "maintenance.manage": "Wartungsmodus verwalten",
  "sso.admin": "SSO/Keycloak verwalten",
  "notify.manage": "Benachrichtigungen verwalten",
  "support.manage": "Support-Tickets verwalten",
  auftrag: "Kundenaufträge & Todos",
  "auftrag.manage": "Alle Aufträge verwalten",
  admin: "System & Berechtigungen",
};

/** Features that every authenticated user gets by default */
export const DEFAULT_ALLOWED: Feature[] = [
  "home",
  "account",
  "settings",
  "chat",
  "news",
  "docs",
  "basics",
  "workspace",
];

/** Every module that an employee needs to see the sidebar */
export const CORE_EMPLOYEE_FEATURES: Feature[] = [
  "home",
  "worktime",
  "tasks",
  "calendar",
  "contacts",
  "chat",
  "vault",
  "workspace",
  "basics",
  "news",
  "docs",
  "apply",
  "teams",
  "security",
  "payments",
  "auftrag",
  "admin",
];
