/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedVaultRouteImport } from './routes/_authenticated/vault'
import { Route as AuthenticatedMailRouteImport } from './routes/_authenticated/mail'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCollectiveRouteImport } from './routes/_authenticated/collective'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedBasicsRouteImport } from './routes/_authenticated/basics'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings.integrations'
import { Route as ApiPublicMailCfInboundRouteImport } from './routes/api/public/mail/cf-inbound'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVaultRoute = AuthenticatedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMailRoute = AuthenticatedMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectiveRoute = AuthenticatedCollectiveRouteImport.update({
  id: '/collective',
  path: '/collective',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBasicsRoute = AuthenticatedBasicsRouteImport.update({
  id: '/basics',
  path: '/basics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicMailCfInboundRoute = ApiPublicMailCfInboundRouteImport.update({
  id: '/api/public/mail/cf-inbound',
  path: '/api/public/mail/cf-inbound',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/basics': typeof AuthenticatedBasicsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/collective': typeof AuthenticatedCollectiveRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/mail': typeof AuthenticatedMailRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/api/public/mail/cf-inbound': typeof ApiPublicMailCfInboundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/basics': typeof AuthenticatedBasicsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/collective': typeof AuthenticatedCollectiveRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/mail': typeof AuthenticatedMailRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/api/public/mail/cf-inbound': typeof ApiPublicMailCfInboundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/basics': typeof AuthenticatedBasicsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/collective': typeof AuthenticatedCollectiveRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/mail': typeof AuthenticatedMailRoute
  '/_authenticated/vault': typeof AuthenticatedVaultRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/api/public/mail/cf-inbound': typeof ApiPublicMailCfInboundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/basics'
    | '/chat'
    | '/collective'
    | '/contacts'
    | '/mail'
    | '/vault'
    | '/workspace'
    | '/settings/integrations'
    | '/api/public/mail/cf-inbound'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/basics'
    | '/chat'
    | '/collective'
    | '/contacts'
    | '/mail'
    | '/vault'
    | '/workspace'
    | '/settings/integrations'
    | '/api/public/mail/cf-inbound'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/basics'
    | '/_authenticated/chat'
    | '/_authenticated/collective'
    | '/_authenticated/contacts'
    | '/_authenticated/mail'
    | '/_authenticated/vault'
    | '/_authenticated/workspace'
    | '/_authenticated/settings/integrations'
    | '/api/public/mail/cf-inbound'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicMailCfInboundRoute: typeof ApiPublicMailCfInboundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vault': {
      id: '/_authenticated/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedVaultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mail': {
      id: '/_authenticated/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof AuthenticatedMailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collective': {
      id: '/_authenticated/collective'
      path: '/collective'
      fullPath: '/collective'
      preLoaderRoute: typeof AuthenticatedCollectiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/basics': {
      id: '/_authenticated/basics'
      path: '/basics'
      fullPath: '/basics'
      preLoaderRoute: typeof AuthenticatedBasicsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/mail/cf-inbound': {
      id: '/api/public/mail/cf-inbound'
      path: '/api/public/mail/cf-inbound'
      fullPath: '/api/public/mail/cf-inbound'
      preLoaderRoute: typeof ApiPublicMailCfInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBasicsRoute: typeof AuthenticatedBasicsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCollectiveRoute: typeof AuthenticatedCollectiveRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedMailRoute: typeof AuthenticatedMailRoute
  AuthenticatedVaultRoute: typeof AuthenticatedVaultRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBasicsRoute: AuthenticatedBasicsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCollectiveRoute: AuthenticatedCollectiveRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedMailRoute: AuthenticatedMailRoute,
  AuthenticatedVaultRoute: AuthenticatedVaultRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicMailCfInboundRoute: ApiPublicMailCfInboundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
