/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedVaultRouteImport } from './routes/_authenticated/vault'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedNotifyRouteImport } from './routes/_authenticated/notify'
import { Route as AuthenticatedNewsRouteImport } from './routes/_authenticated/news'
import { Route as AuthenticatedMailRouteImport } from './routes/_authenticated/mail'
import { Route as AuthenticatedFinancesRouteImport } from './routes/_authenticated/finances'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCollectiveRouteImport } from './routes/_authenticated/collective'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBasicsRouteImport } from './routes/_authenticated/basics'
import { Route as AuthenticatedAppsRouteImport } from './routes/_authenticated/apps'
import { Route as AuthenticatedSettingsTabsRouteImport } from './routes/_authenticated/settings.tabs'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings.integrations'
import { Route as AuthenticatedSettingsDesignRouteImport } from './routes/_authenticated/settings.design'
import { Route as ApiPublicMailCfInboundRouteImport } from './routes/api/public/mail/cf-inbound'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVaultRoute = AuthenticatedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotifyRoute = AuthenticatedNotifyRouteImport.update({
  id: '/notify',
  path: '/notify',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsRoute = AuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMailRoute = AuthenticatedMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinancesRoute = AuthenticatedFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectiveRoute = AuthenticatedCollectiveRouteImport.update({
  id: '/collective',
  path: '/collective',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBasicsRoute = AuthenticatedBasicsRouteImport.update({
  id: '/basics',
  path: '/basics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsRoute = AuthenticatedAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsTabsRoute =
  AuthenticatedSettingsTabsRouteImport.update({
    id: '/settings/tabs',
    path: '/settings/tabs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsDesignRoute =
  AuthenticatedSettingsDesignRouteImport.update({
    id: '/settings/design',
    path: '/settings/design',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicMailCfInboundRoute = ApiPublicMailCfInboundRouteImport.update({
  id: '/api/public/mail/cf-inbound',
  path: '/api/public/mail/cf-inbound',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/apps': typeof AuthenticatedAppsRoute
  '/basics': typeof AuthenticatedBasicsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/chat': typeof AuthenticatedChatRoute
  '/collective': typeof AuthenticatedCollectiveRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/mail': typeof AuthenticatedMailRoute
  '/news': typeof AuthenticatedNewsRoute
  '/notify': typeof AuthenticatedNotifyRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/settings/design': typeof AuthenticatedSettingsDesignRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/tabs': typeof AuthenticatedSettingsTabsRoute
  '/api/public/mail/cf-inbound': typeof ApiPublicMailCfInboundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/apps': typeof AuthenticatedAppsRoute
  '/basics': typeof AuthenticatedBasicsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/chat': typeof AuthenticatedChatRoute
  '/collective': typeof AuthenticatedCollectiveRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/mail': typeof AuthenticatedMailRoute
  '/news': typeof AuthenticatedNewsRoute
  '/notify': typeof AuthenticatedNotifyRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/settings/design': typeof AuthenticatedSettingsDesignRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/tabs': typeof AuthenticatedSettingsTabsRoute
  '/api/public/mail/cf-inbound': typeof ApiPublicMailCfInboundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/apps': typeof AuthenticatedAppsRoute
  '/_authenticated/basics': typeof AuthenticatedBasicsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/collective': typeof AuthenticatedCollectiveRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/finances': typeof AuthenticatedFinancesRoute
  '/_authenticated/mail': typeof AuthenticatedMailRoute
  '/_authenticated/news': typeof AuthenticatedNewsRoute
  '/_authenticated/notify': typeof AuthenticatedNotifyRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/vault': typeof AuthenticatedVaultRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/_authenticated/settings/design': typeof AuthenticatedSettingsDesignRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/settings/tabs': typeof AuthenticatedSettingsTabsRoute
  '/api/public/mail/cf-inbound': typeof ApiPublicMailCfInboundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/apps'
    | '/basics'
    | '/calendar'
    | '/chat'
    | '/collective'
    | '/contacts'
    | '/finances'
    | '/mail'
    | '/news'
    | '/notify'
    | '/permissions'
    | '/security'
    | '/support'
    | '/tasks'
    | '/vault'
    | '/workspace'
    | '/settings/design'
    | '/settings/integrations'
    | '/settings/tabs'
    | '/api/public/mail/cf-inbound'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/apps'
    | '/basics'
    | '/calendar'
    | '/chat'
    | '/collective'
    | '/contacts'
    | '/finances'
    | '/mail'
    | '/news'
    | '/notify'
    | '/permissions'
    | '/security'
    | '/support'
    | '/tasks'
    | '/vault'
    | '/workspace'
    | '/settings/design'
    | '/settings/integrations'
    | '/settings/tabs'
    | '/api/public/mail/cf-inbound'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/apps'
    | '/_authenticated/basics'
    | '/_authenticated/calendar'
    | '/_authenticated/chat'
    | '/_authenticated/collective'
    | '/_authenticated/contacts'
    | '/_authenticated/finances'
    | '/_authenticated/mail'
    | '/_authenticated/news'
    | '/_authenticated/notify'
    | '/_authenticated/permissions'
    | '/_authenticated/security'
    | '/_authenticated/support'
    | '/_authenticated/tasks'
    | '/_authenticated/vault'
    | '/_authenticated/workspace'
    | '/_authenticated/settings/design'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/tabs'
    | '/api/public/mail/cf-inbound'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicMailCfInboundRoute: typeof ApiPublicMailCfInboundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vault': {
      id: '/_authenticated/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedVaultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notify': {
      id: '/_authenticated/notify'
      path: '/notify'
      fullPath: '/notify'
      preLoaderRoute: typeof AuthenticatedNotifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news': {
      id: '/_authenticated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mail': {
      id: '/_authenticated/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof AuthenticatedMailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finances': {
      id: '/_authenticated/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AuthenticatedFinancesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collective': {
      id: '/_authenticated/collective'
      path: '/collective'
      fullPath: '/collective'
      preLoaderRoute: typeof AuthenticatedCollectiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/basics': {
      id: '/_authenticated/basics'
      path: '/basics'
      fullPath: '/basics'
      preLoaderRoute: typeof AuthenticatedBasicsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps': {
      id: '/_authenticated/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/tabs': {
      id: '/_authenticated/settings/tabs'
      path: '/settings/tabs'
      fullPath: '/settings/tabs'
      preLoaderRoute: typeof AuthenticatedSettingsTabsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/design': {
      id: '/_authenticated/settings/design'
      path: '/settings/design'
      fullPath: '/settings/design'
      preLoaderRoute: typeof AuthenticatedSettingsDesignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/mail/cf-inbound': {
      id: '/api/public/mail/cf-inbound'
      path: '/api/public/mail/cf-inbound'
      fullPath: '/api/public/mail/cf-inbound'
      preLoaderRoute: typeof ApiPublicMailCfInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppsRoute: typeof AuthenticatedAppsRoute
  AuthenticatedBasicsRoute: typeof AuthenticatedBasicsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCollectiveRoute: typeof AuthenticatedCollectiveRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedFinancesRoute: typeof AuthenticatedFinancesRoute
  AuthenticatedMailRoute: typeof AuthenticatedMailRoute
  AuthenticatedNewsRoute: typeof AuthenticatedNewsRoute
  AuthenticatedNotifyRoute: typeof AuthenticatedNotifyRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedVaultRoute: typeof AuthenticatedVaultRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
  AuthenticatedSettingsDesignRoute: typeof AuthenticatedSettingsDesignRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedSettingsTabsRoute: typeof AuthenticatedSettingsTabsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppsRoute: AuthenticatedAppsRoute,
  AuthenticatedBasicsRoute: AuthenticatedBasicsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCollectiveRoute: AuthenticatedCollectiveRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedFinancesRoute: AuthenticatedFinancesRoute,
  AuthenticatedMailRoute: AuthenticatedMailRoute,
  AuthenticatedNewsRoute: AuthenticatedNewsRoute,
  AuthenticatedNotifyRoute: AuthenticatedNotifyRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedVaultRoute: AuthenticatedVaultRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
  AuthenticatedSettingsDesignRoute: AuthenticatedSettingsDesignRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
  AuthenticatedSettingsTabsRoute: AuthenticatedSettingsTabsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicMailCfInboundRoute: ApiPublicMailCfInboundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
